class FeeCategory {
  final String id;
  final String accountId;
  final String name;
  final String? description;
  final bool isActive;
  final DateTime createdAt;
  final DateTime updatedAt;

  FeeCategory({
    required this.id,
    required this.accountId,
    required this.name,
    this.description,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
  });

  factory FeeCategory.fromJson(Map<String, dynamic> json) {
    return FeeCategory(
      id: json['id'],
      accountId: json['account_id'],
      name: json['name'],
      description: json['description'],
      isActive: json['is_active'] ?? true,
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'account_id': accountId,
      'name': name,
      'description': description,
      'is_active': isActive,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class FeeStructure {
  final String id;
  final String accountId;
  final String categoryId;
  final String name;
  final double amount;
  final String studentClass;
  final DateTime? dueDate;
  final String? description;
  final bool isActive;
  final String planType;
  final double lateFine;
  final int graceDays;
  final double gstPercent;
  final bool autoGenerateDues;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String? categoryName;

  FeeStructure({
    required this.id,
    required this.accountId,
    required this.categoryId,
    required this.name,
    required this.amount,
    required this.studentClass,
    this.dueDate,
    this.description,
    required this.isActive,
    required this.planType,
    required this.lateFine,
    required this.graceDays,
    required this.gstPercent,
    required this.autoGenerateDues,
    required this.createdAt,
    required this.updatedAt,
    this.categoryName,
  });

  factory FeeStructure.fromJson(Map<String, dynamic> json) {
    return FeeStructure(
      id: json['id'],
      accountId: json['account_id'],
      categoryId: json['category_id'],
      name: json['name'],
      amount: double.parse(json['amount'].toString()),
      studentClass: json['class'],
      dueDate: json['due_date'] != null ? DateTime.parse(json['due_date']) : null,
      description: json['description'],
      isActive: json['is_active'] ?? true,
      planType: json['plan_type'] ?? 'monthly',
      lateFine: double.parse((json['late_fine'] ?? 0).toString()),
      graceDays: json['grace_days'] ?? 0,
      gstPercent: double.parse((json['gst_percent'] ?? 0).toString()),
      autoGenerateDues: json['auto_generate_dues'] ?? true,
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
      categoryName: json['fee_categories']?['name'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'account_id': accountId,
      'category_id': categoryId,
      'name': name,
      'amount': amount,
      'class': studentClass,
      'due_date': dueDate?.toIso8601String(),
      'description': description,
      'is_active': isActive,
      'plan_type': planType,
      'late_fine': lateFine,
      'grace_days': graceDays,
      'gst_percent': gstPercent,
      'auto_generate_dues': autoGenerateDues,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

class FeeAssignment {
  final String id;
  final String accountId;
  final String studentId;
  final String feeStructureId;
  final DateTime startDate;
  final double discountAmount;
  final String? waiverReason;
  final bool isActive;
  final DateTime createdAt;
  final DateTime updatedAt;
  final FeeStructure? feeStructure;

  FeeAssignment({
    required this.id,
    required this.accountId,
    required this.studentId,
    required this.feeStructureId,
    required this.startDate,
    required this.discountAmount,
    this.waiverReason,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
    this.feeStructure,
  });

  factory FeeAssignment.fromJson(Map<String, dynamic> json) {
    return FeeAssignment(
      id: json['id'],
      accountId: json['account_id'],
      studentId: json['student_id'],
      feeStructureId: json['fee_structure_id'],
      startDate: DateTime.parse(json['start_date']),
      discountAmount: double.parse((json['discount_amount'] ?? 0).toString()),
      waiverReason: json['waiver_reason'],
      isActive: json['is_active'] ?? true,
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
      feeStructure: json['fee_structures'] != null 
        ? FeeStructure.fromJson(json['fee_structures']) 
        : null,
    );
  }
}

class Due {
  final String id;
  final String accountId;
  final String studentId;
  final String? feeStructureId;
  final String? batchId;
  final String periodName;
  final DateTime dueDate;
  final double amountAssigned;
  final double amountPaid;
  final double dueAmount;
  final double lateFineApplied;
  final String status;
  final String? notes;
  final DateTime createdAt;
  final DateTime updatedAt;
  final FeeStructure? feeStructure;

  Due({
    required this.id,
    required this.accountId,
    required this.studentId,
    this.feeStructureId,
    this.batchId,
    required this.periodName,
    required this.dueDate,
    required this.amountAssigned,
    required this.amountPaid,
    required this.dueAmount,
    required this.lateFineApplied,
    required this.status,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
    this.feeStructure,
  });

  factory Due.fromJson(Map<String, dynamic> json) {
    return Due(
      id: json['id'],
      accountId: json['account_id'],
      studentId: json['student_id'],
      feeStructureId: json['fee_structure_id'],
      batchId: json['batch_id'],
      periodName: json['period_name'],
      dueDate: DateTime.parse(json['due_date']),
      amountAssigned: double.parse(json['amount_assigned'].toString()),
      amountPaid: double.parse((json['amount_paid'] ?? 0).toString()),
      dueAmount: double.parse((json['due_amount'] ?? 0).toString()),
      lateFineApplied: double.parse((json['late_fine_applied'] ?? 0).toString()),
      status: json['status'],
      notes: json['notes'],
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
      feeStructure: json['fee_structures'] != null 
        ? FeeStructure.fromJson(json['fee_structures']) 
        : null,
    );
  }

  String get formattedPeriodName {
    // Strips out "Batch <uuid> " from the periodName
    // UUIDs are 36 characters long. e.g., "Batch 9c7835e3-8ee6-4cfa-99fd-a3e8922a0389 Jun 2026" -> "Jun 2026"
    final regex = RegExp(r'^Batch [a-fA-F0-9\-]{36}\s+');
    final cleaned = periodName.replaceAll(regex, '');
    
    // Add "Fee" suffix if it's just a month/year or quarter to make it look better
    if (cleaned.contains(RegExp(r'^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4}$')) || 
        cleaned.contains(RegExp(r'^Q[1-4]\s+\d{4}$'))) {
      return '$cleaned Fee';
    }
    return cleaned;
  }
}

