// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-vie4IU2BTDJKeNcAShEsud_qBk6Eig',
    appId: '1:476631174963:web:27ea0dd74c283aa00ab846',
    messagingSenderId: '476631174963',
    projectId: 'feesync-5fcfc',
    authDomain: 'feesync-5fcfc.firebaseapp.com',
    storageBucket: 'feesync-5fcfc.firebasestorage.app',
    measurementId: 'G-LF3S41RNZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJpVVJwc-AmNk1tnFWhvRdojRoqHMqdSE',
    appId: '1:476631174963:android:3c79259fcce74a540ab846',
    messagingSenderId: '476631174963',
    projectId: 'feesync-5fcfc',
    storageBucket: 'feesync-5fcfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nQ9OXLiLmuQ-zPck7Hfw4HhdsK0h3s4',
    appId: '1:476631174963:ios:0c703882a99c408b0ab846',
    messagingSenderId: '476631174963',
    projectId: 'feesync-5fcfc',
    storageBucket: 'feesync-5fcfc.firebasestorage.app',
    iosBundleId: 'com.feesync.feesyncMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nQ9OXLiLmuQ-zPck7Hfw4HhdsK0h3s4',
    appId: '1:476631174963:ios:0c703882a99c408b0ab846',
    messagingSenderId: '476631174963',
    projectId: 'feesync-5fcfc',
    storageBucket: 'feesync-5fcfc.firebasestorage.app',
    iosBundleId: 'com.feesync.feesyncMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-vie4IU2BTDJKeNcAShEsud_qBk6Eig',
    appId: '1:476631174963:web:9be81cfce9b5ba9c0ab846',
    messagingSenderId: '476631174963',
    projectId: 'feesync-5fcfc',
    authDomain: 'feesync-5fcfc.firebaseapp.com',
    storageBucket: 'feesync-5fcfc.firebasestorage.app',
    measurementId: 'G-Q6RKEZEB50',
  );
}
