import 'dart:io';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../models/student.dart';

class ReceiptService {
  static Future<File> generatePdfReceipt({
    required Student student,
    required double amount,
    required String paymentMode,
    required DateTime date,
    required String invoiceNo,
  }) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('dd MMM yyyy').format(date);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a5,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('PAYMENT RECEIPT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text('FeeSync', style: pw.TextStyle(fontSize: 16, color: PdfColors.grey700)),
                  ],
                ),
                pw.Divider(thickness: 2),
                pw.SizedBox(height: 20),
                _buildPdfRow('Invoice No:', invoiceNo),
                _buildPdfRow('Date:', dateStr),
                pw.SizedBox(height: 10),
                _buildPdfRow('Student:', student.fullName),
                _buildPdfRow('Class:', student.studentClass),
                if (student.rollNumber != null) _buildPdfRow('Roll No:', student.rollNumber!),
                pw.SizedBox(height: 20),
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Amount Paid:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('INR ${amount.toStringAsFixed(2)}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                    ],
                  ),
                ),
                pw.SizedBox(height: 10),
                _buildPdfRow('Payment Mode:', paymentMode.toUpperCase()),
                _buildPdfRow('Status:', 'SUCCESSFUL'),
                pw.Spacer(),
                pw.Center(
                  child: pw.Text('This is a computer generated receipt.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                ),
              ],
            ),
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/receipt_$invoiceNo.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildPdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static String generateTextReceipt({
    required Student student,
    required double amount,
    required String paymentMode,
    required DateTime date,
    required String invoiceNo,
  }) {
    final dateStr = DateFormat('dd MMM yyyy').format(date);
    return """
📝 *PAYMENT RECEIPT*
--------------------------
*Invoice No:* $invoiceNo
*Date:* $dateStr
--------------------------
*Student:* ${student.fullName}
*Class:* ${student.studentClass}
*Amount Paid:* ₹${amount.toStringAsFixed(0)}
*Payment Mode:* ${paymentMode.toUpperCase()}
--------------------------
*Status:* ✅ SUCCESSFUL

Thank you for the payment!
_Generated by FeeSync_
""";
  }

  static Future<void> shareToWhatsApp({
    required String phone,
    required String text,
    File? pdfFile,
  }) async {
    if (pdfFile != null) {
      // Direct file sharing to a specific number is not supported by system share sheets,
      // so we use the standard share sheet which allows selecting WhatsApp.
      await SharePlus.instance.share(
        ShareParams(files: [XFile(pdfFile.path)], text: text),
      );
    } else if (phone.isNotEmpty) {
      // For text-only receipts, we can target the number directly.
      final cleanPhone = phone.replaceAll(RegExp(r'[^0-9]'), '');
      final url = 'https://wa.me/$cleanPhone?text=${Uri.encodeComponent(text)}';
      if (await canLaunchUrl(Uri.parse(url))) {
        await launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);
      } else {
        await SharePlus.instance.share(ShareParams(text: text));
      }
    } else {
      await SharePlus.instance.share(ShareParams(text: text));
    }
  }
}
